# Generated by Django 5.2.8 on 2025-12-10 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('charge', 'Charge'), ('refund', 'Refund')], max_length=10)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customer')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
