# Generated by Django 5.2.9 on 2025-12-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderassignment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ON_THE_WAY', 'On the way'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20),
        ),
    ]
