# Generated by Django 5.2.8 on 2025-11-10 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0002_initial'),
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed_by_is_vip', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('weight', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints_filed', to=settings.AUTH_USER_MODEL)),
                ('target_chef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.chef')),
                ('target_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.driver')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='reputation.complaint')),
                ('disputed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
