# Generated by Django 5.2.8 on 2025-12-11 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('hr', '0002_registrationapproval_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationapproval',
            name='manager_id',
        ),
        migrations.AddField(
            model_name='registrationapproval',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.manager'),
        ),
    ]
