from django.db import transaction
from django.db.models import Q
from .models import KBEntry, AIAnswer, AIRating, KBFlag
from accounts.models import Customer

class AIService:
    @staticmethod
    def ask_question(customer_id, question_text):
        """
        UC20: Answers a question.
        Priority:
        1. Local KB (Exact or keyword match)
        2. External LLM (Fallback)
        """
        # 1. Search KB (Simple keyword match for now)
        # (In production, use vector search or fuzzy matching)
        kb_match = KBEntry.objects.filter(
            question__icontains=question_text, 
            active=True
        ).first()

        if kb_match:
            # Source: KB
            answer = AIAnswer.objects.create(
                kb_id=kb_match,
                question=question_text,
                answer=kb_match.answer,
                source="kb"
            )
        else:
            # Source: LLM (Simulated)
            # TODO: Plug in Ollama logic here
            fake_llm_response = f"AI Response to '{question_text}' (Generated by LLM)"
            answer = AIAnswer.objects.create(
                kb_id=None,
                question=question_text,
                answer=fake_llm_response,
                source="llm"
            )

        return True, "Answer generated", answer

    @staticmethod
    def submit_rating(customer_id, ai_answer_id, stars):
        """
        UC21: Rate an answer.
        Logic: If stars == 0 and source was KB, flag the KB entry.
        """
        try:
            stars = int(stars)
            if not (0 <= stars <= 5):
                return False, "Stars must be between 0 and 5"
            
            # 1. Save Rating
            ai_answer = AIAnswer.objects.get(pk=ai_answer_id)
            customer = Customer.objects.get(pk=customer_id)
            
            AIRating.objects.create(
                customer_id=customer,
                ai_answer_id=ai_answer,
                stars=stars
            )

            # 2. Flag Logic (UC21)
            # If rating is 0 AND it came from a KB entry, flag it.
            if stars == 0 and ai_answer.source == "kb" and ai_answer.kb_id:
                KBFlag.objects.get_or_create(
                    customer_id=customer,
                    report_id=ai_answer.kb_id, # Link flag to the KB Entry
                    defaults={'reason': "Rated 0 stars by user"}
                )
                return True, "Rating submitted. KB Entry has been flagged for review."

            return True, "Rating submitted."

        except AIAnswer.DoesNotExist:
            return False, "Answer not found."
        except Customer.DoesNotExist:
            return False, "Customer not found."
        except Exception as e:
            return False, str(e)